export default Avengers = [
  {
    id: "1",
    imageSrc: "https://avatars.githubusercontent.com/ap221882",
    name: "Ajay Pathak",
    place: "Gurugram, Haryana",
    company: "Naehas Inc",
    designation: "Frontend Developer",
  },
  {
    id: "2",
    imageSrc: "",
    name: "Balaji Gaikwad",
    place: "Pune, Maharashtra",
    company: "Nice Ltd",
    designation: "Senior Software Engineer",
  },
  {
    id: "3",
    imageSrc: "",
    name: "Chaitra J",
    place: "Bengaluru, Karnataka",
    company: "Wells Fargo",
    designation: "Senior Software Engineer",
  },
  {
    id: "4",
    imageSrc: "",
    name: "Gourav Goswami",
    place: "Madhya Pradesh",
    company: "Toschi Infotech",
    designation: "Frontend Developer",
  },
  {
    id: "5",
    imageSrc: "",
    name: "Kirti Sahai",
    place: "New Delhi",
    company: "Kongsberg Digital",
    designation: "Senior Frontend Developer",
  },
  {
    id: "6",
    imageSrc: "",
    name: "Laxmi Waghmore",
    place: "Mumbai, Maharashtra",
    company: "Cognizant",
    designation: "Frontend Developer",
  },
  {
    id: "7",
    imageSrc: "",
    name: "Mallikarjun K Basavanagowdra",
    place: "Bengaluru, Karnataka",
    company: "William O'Neil India",
    designation: "Software Engineer",
  },
  {
    id: "8",
    imageSrc: "",
    name: "Pujarini Jena",
    place: "Gurugram, Haryana",
    company: "CARS24",
    designation: "Software Engineer",
  },
  {
    id: "9",
    imageSrc: "",
    name: "Roshan Trivedi",
    place: "Muzaffarpur, Bihar",
    company: "Infosys",
    designation: "",
  },
  {
    id: "10",
    imageSrc: "",
    name: "Vijesh N K",
    place: "Mangalore, Karnataka",
    company: "Pace wisdom solutions",
    designation: "",
  },
];
